# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180603_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Value',
            new_name='Value0',
        ),
    ]
