# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180618_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Value1',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Value2',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Value0',
            field=models.FloatField(default=0.0),
        ),
    ]
