# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180626_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='Value2',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Value3',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Value4',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Value5',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Value6',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Value7',
        ),
        migrations.RemoveField(
            model_name='input',
            name='Value8',
        ),
    ]
