# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180626_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='Value2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='input',
            name='Value3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='input',
            name='Value4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='input',
            name='Value5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='input',
            name='Value6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='input',
            name='Value7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='input',
            name='Value8',
            field=models.FloatField(default=0.0),
        ),
    ]
