# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180626_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value1', models.FloatField(default=0.0)),
                ('Value2', models.FloatField(default=0.0)),
                ('Value3', models.FloatField(default=0.0)),
                ('Value4', models.FloatField(default=0.0)),
                ('Value5', models.FloatField(default=0.0)),
                ('Value6', models.FloatField(default=0.0)),
                ('Value7', models.FloatField(default=0.0)),
                ('Value8', models.FloatField(default=0.0)),
            ],
        ),
    ]
