# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='Value1',
            field=models.FloatField(),
        ),
    ]
